[package]
name = "rust-fractal"
version = "0.1.0"
authors = ["jackyarndley <34801340+jackyarndley@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "0.22.3"
rayon = "1.3.0"
packed_simd = "0.3.3"