[package]
name = "rust_fractal"
version = "0.1.0"
authors = ["jackyarndley <34801340+jackyarndley@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "0.22.3"
rand = "0.7.3"
num-complex = "0.2.4"
pbr = "1.0.2"
ispc = "^1.0.4"

[build-dependencies]
ispc = "^1.0.4"