image_width = 1000
image_height = 1000
rotate = 0
approximation_order = 0
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = false
auto_adjust_iterations = true
probe_sampling = 3
remove_centre = true
export = "png"