image_width = 1920
image_height = 1080
rotate = 0
approximation_order = 64
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = true
auto_adjust_iterations = true
remove_centre = true
export = "png"

# By default this is squared tolerance. 1e-6 works normally, 1.4e-6 is low tolerance.
glitch_tolerance = 1.4e-6

probe_sampling = 15

# These are experimental options following
experimental = true 

# If this is set higher than the maximum iteration value this will cause any additional glitches to be perturbed without series approximation
high_precision_data_interval = 100
valid_iteration_frame_multiplier = 0.05
valid_iteration_probe_multiplier = 0.005