image_width = 1920
image_height = 1080
rotate = 0
approximation_order = 64
glitch_tolerance = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = false
auto_adjust_iterations = true
probe_sampling = 15
remove_centre = false
export = "png"


# These are experimental options
experimental = true 
high_precision_data_interval = 100