image_width = 8192
image_height = 8192
rotate = 0
approximation_order = 64
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = true
auto_adjust_iterations = true
probe_sampling = 12
remove_centre = false
export = "png"

# These are experimental options
experimental = true 
high_precision_data_interval = 100
valid_iteration_frame_multiplier = 0.75
valid_iteration_probe_multiplier = 0.98
glitch_tolerance = 1.25e-6