image_width = 500
image_height = 500
rotate = 0
approximation_order = 16
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = false
auto_adjust_iterations = true
probe_sampling = 2
remove_centre = true
export = "png"